from enum import Enum

class Command(Enum):
    ADD = "add contact"
    DELETE = "delete contact"
    SHOW = "show contacts"
    SEARCH = "search contact"
    EDIT = "edit contact"
    HELP = "help"
    EXIT = "exit"
    HELLO = "hello"
    UPCOMING_BIRTHDAYS = "upcoming birthdays"
    ADD_NOTE = "add note"
    DELETE_NOTE = "delete note"
    EDIT_NOTE_TITLE = "edit note title"
    EDIT_NOTE_DESCRIPTION = "edit note description"
    EDIT_NOTE_TAG = "edit note tag"
    SEARCH_NOTE = "search note"
    SEARCH_NOTE_BY_TAG = "search note by tag"
    SHOW_NOTES = "show notes"
    SORTED_NOTES = "sorted notes"
